spring.application.name=gateway

server.port=8080

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URI:http://localhost:8083}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/login,/api/auth/validate,/api/auth/refresh

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=${USER_SERVICE_URI:http://localhost:8081}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**,/api/cards/**

spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=${ORDER_SERVICE_URI:http://localhost:8082}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**,/api/v1/items/**

app.jwt.secret=${JWT_SECRET}
app.jwt.issuer=auth-service

app.security.public-paths[0]=/api/auth/login
app.security.public-paths[1]=/api/auth/register
app.security.public-paths[2]=/api/auth/refresh
app.security.public-paths[3]=/api/auth/validate

app.services.auth-uri=${AUTH_SERVICE_URI:http://localhost:8083}
app.services.user-uri=${USER_SERVICE_URI:http://localhost:8081}
